# models.py
MIN_VALUE_COOKING_TIME = 1
MAX_VALUE_COOKING_TIME = 32_000

MIN_VALUE_INGREDIENT_AMOUNT = 1
MAX_VALUE_INGREDIENT_AMOUNT = 32_000

MAX_LENGTH_RECIPE_NAME = 256

MAX_LENGTH_INGREDIENT_NAME = 256
MAX_LENGTH_MEASUREMENT_UNIT = 64

RECIPE_IMAGES_PATH = 'recipes/'
